path_to_data: "./data.nosync/all_data_bvp-filt.parquet"
path_to_save_folder: "./data.nosync"
save_format: 'parquet'
window_size: 32 # the window size is 1sec, i.e. 32 samples, since the frequency of the ACC is 32Hz
plots: True
clean_plots: True
